# Iris Docker Compose - Ultra Fast Multi-Service Setup
version: '3.8'

services:
  # Redis for Dramatiq worker
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Backend API + Worker
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.0-flash-exp}
      - GEMINI_THINKING_BUDGET=${GEMINI_THINKING_BUDGET:-medium}
      - TOOL_CACHE_TTL=${TOOL_CACHE_TTL:-300}
      - JOB_TTL=${JOB_TTL:-3600}
      - EVENT_TTL=${EVENT_TTL:-1800}
      - MAX_EVENTS_PER_JOB=${MAX_EVENTS_PER_JOB:-1000}
      - STREAMING_ENABLED=${STREAMING_ENABLED:-true}
      - PARALLEL_TOOLS=${PARALLEL_TOOLS:-true}
      - WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED:-true}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DAYTONA_API_KEY=${DAYTONA_API_KEY}
      - DAYTONA_WORKSPACE_ID=${DAYTONA_WORKSPACE_ID:-test-workspace-123}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - WEB_SEARCH_TIMEOUT_MS=${WEB_SEARCH_TIMEOUT_MS:-1500}
      - SCRAPE_TIMEOUT_MS=${SCRAPE_TIMEOUT_MS:-2000}
      - DAYTONA_TIMEOUT_MS=${DAYTONA_TIMEOUT_MS:-5000}
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock  # For Daytona sandbox
    command: >
      sh -c "
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload &
        dramatiq workers.main &
        wait
      "

  # Frontend - Sleek Dashboard
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  redis_data:
